from typing import List, Protocol, runtime_checkable
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Represents a conversational message in a chat history."""
    role: str = Field(..., description="Role of the speaker: 'user', 'assistant', or 'system'")
    content: str = Field(..., description="Message text content")


class LLMProviderError(Exception):
    """Exception raised for LLM provider failures."""
    pass


@runtime_checkable
class LLMProvider(Protocol):
    """Abstract protocol for an LLM runtime provider."""

    async def get_agent_reply(self, messages: List[ChatMessage]) -> str:
        """Generate an agent reply given a conversation history.
        
        Args:
            messages: Ordered list of prior messages in the conversation.
            
        Returns:
            The textual assistant reply.
            
        Raises:
            LLMProviderError: If the underlying model call fails.
        """
        ...


async def get_agent_reply(messages: List[ChatMessage], provider: LLMProvider) -> str:
    """High-level abstraction for generating an agent reply.
    
    Args:
        messages: Conversation messages to pass to the model.
        provider: An instance satisfying the LLMProvider protocol.
        
    Returns:
        The text response generated by the provider.
    """
    return await provider.get_agent_reply(messages)
